language: ruby
sudo: false
rvm:
  - 2.2
  - 2.3
  - 2.4
before_install:
  - gem update --system
  - gem install bundler -v 2.1.1
gemfile:
  - gemfiles/middleman_4.3.gemfile
  - gemfiles/middleman_master.gemfile
